### ISSUE TITLE
Why is the NuGet package unlisted?

### ISSUE THREAD

**Issue by mikhailshilkov** [Silv3rcircl3/Akka.Streams.Azure#1]
Why is the NuGet package unlisted? I'd love to play with the library.

**Comment by marcpiechura** [comment]
Hi @mikhailshilkov,

I haven't expected that anyone would already playing with it and after I published it I fixed some parts and wanted to republish it again but I hadn't had the time to do so. 
I will rewrite the ServiceBus stage and fix #2 tomorrow and then release a new version on nuget.

**Comment by marcpiechura** [comment]
I also have listed the current version again.
